import type { Metadata } from "next";

export const SITE_URL = "https://www.evainteligencia.com.br";

/**
 * Metadata for a public page: title, description, canonical URL and the
 * share image generated by scripts/generate-og.mjs (public/og/<og>.png).
 * Paths end with "/" because the site is exported with trailingSlash.
 */
export function pageMeta({
  path,
  title,
  description,
  og,
}: {
  path: string;
  title: string;
  description: string;
  og: string;
}): Metadata {
  const image = { url: `/og/${og}.png`, width: 1200, height: 630, alt: title };
  return {
    title,
    description,
    alternates: { canonical: path },
    openGraph: {
      type: "website",
      locale: "pt_BR",
      siteName: "Eva Inteligência",
      url: path,
      title,
      description,
      images: [image],
    },
    twitter: { card: "summary_large_image", title, description, images: [image.url] },
  };
}

/** Pages listed in the sitemap, in order of importance. */
export const PUBLIC_PAGES = [
  { path: "/", priority: 1 },
  { path: "/planos/", priority: 0.9 },
  { path: "/produtos/", priority: 0.9 },
  { path: "/eva-ia/", priority: 0.8 },
  { path: "/central-de-ajuda/", priority: 0.6 },
  { path: "/sobre/", priority: 0.6 },
  { path: "/eva-club/", priority: 0.6 },
  { path: "/afiliados/", priority: 0.6 },
  { path: "/suporte/", priority: 0.5 },
];
